//============================
//  by CJ
//============================
struct VertIn
{
	float4 pos : POSITION;
	float4 diffuse : COLOR0;
	float2 tex0 : TEXCOORD0;
};

struct VertOut
{
	float4 pos : POSITION;
	float4 col : COLOR0;
	float2 tex0 : TEXCOORD0;
};

VertOut main(VertIn vin, uniform float4x4 ModelViewProj)
{
	VertOut vout;

	vout.pos = mul(ModelViewProj, vin.pos);
	vout.col = vin.diffuse;
	vout.tex0 = vin.tex0;

	return vout;
}