// SkillManager.h: interface for the CSkillManager class.
//////////////////////////////////////////////////////////////////////
#pragma once

enum ActionSkillType
{
	AT_SKILL_POISON	= 1,
	AT_SKILL_METEO,
	AT_SKILL_THUNDER,
	AT_SKILL_FIREBALL,
	AT_SKILL_FLAME,
	AT_SKILL_TELEPORT,
	AT_SKILL_SLOW,
	AT_SKILL_STORM,
	AT_SKILL_EVIL,
	AT_SKILL_HELL,
	AT_SKILL_POWERWAVE,
	AT_SKILL_FLASH,
	AT_SKILL_BLAST,
	AT_SKILL_INFERNO,
	AT_SKILL_TELEPORT_B,
	AT_SKILL_WIZARDDEFENSE,
	AT_SKILL_ENERGYBALL,
	AT_SKILL_BLAST_POISON = 38,
	AT_SKILL_BLAST_FREEZE,
	AT_SKILL_BLAST_HELL,
	AT_SKILL_BLAST_HELL_BEGIN = 58,
	AT_SKILL_BLOCKING = 18,
	AT_SKILL_SWORD1,
	AT_SKILL_SWORD2,
	AT_SKILL_SWORD3,
	AT_SKILL_SWORD4,
	AT_SKILL_SWORD5,
	AT_SKILL_SPEAR = 47,
	AT_SKILL_VITALITY,
	AT_SKILL_RIDER,
	AT_SKILL_CROSSBOW = 24,
	AT_SKILL_BOW,
	AT_SKILL_HEALING,
	AT_SKILL_DEFENSE,
	AT_SKILL_ATTACK,
	AT_SKILL_SUMMON = 30,
	AT_SKILL_PARALYZE = 51,
	AT_SKILL_PIERCING,
	AT_SKILL_IMPROVE_AG,
	AT_SKILL_BLAST_CROSSBOW4,
	AT_SKILL_REDUCEDEFENSE,
	AT_SKILL_ICE_BLADE,
	AT_SKILL_WHEEL = 41,
	AT_SKILL_FURY_STRIKE,
	AT_SKILL_ONETOONE,
	AT_SKILL_RUSH,
	AT_SKILL_JAVELIN,
	AT_SKILL_DEEPIMPACT,
	AT_SKILL_ONEFLASH = 57,
	AT_SKILL_BOSS = 50,	
	AT_SKILL_COMBO = 59,
	AT_SKILL_STRONG_PIER,
	AT_SKILL_LONGPIER_ATTACK,
	AT_SKILL_DARK_HORSE,
	AT_SKILL_PARTY_TELEPORT,
	AT_SKILL_ADD_CRITICAL,
	AT_SKILL_THUNDER_STRIKE,
	AT_SKILL_LONG_SPEAR,
	AT_SKILL_STUN,
	AT_SKILL_REMOVAL_STUN,
	AT_SKILL_MANA,
	AT_SKILL_INVISIBLE,
	AT_SKILL_REMOVAL_INVISIBLE,
	AT_SKILL_REMOVAL_BUFF,
	AT_SKILL_DEATH_CANNON,
	AT_SKILL_SPACE_SPLIT,
	AT_SKILL_BRAND_OF_SKILL,
	AT_SKILL_PLASMA_STORM_FENRIR = 76,
	AT_SKILL_INFINITY_ARROW,
	AT_SKILL_DARK_SCREAM,
	AT_SKILL_EXPLODE,
	AT_IMPROVE_DAMAGE,
	AT_IMPROVE_MAGIC,
	AT_IMPROVE_CURSE,
	AT_IMPROVE_BLOCKING,
	AT_IMPROVE_DEFENSE,
	AT_LUCK,
	AT_LIFE_REGENERATION,
	AT_IMPROVE_LIFE,
	AT_IMPROVE_MANA,
	AT_DECREASE_DAMAGE,
	AT_REFLECTION_DAMAGE,
	AT_IMPROVE_BLOCKING_PERCENT,
	AT_IMPROVE_GAIN_GOLD,
	AT_EXCELLENT_DAMAGE,
	AT_IMPROVE_DAMAGE_LEVEL,
	AT_IMPROVE_DAMAGE_PERCENT,
	AT_IMPROVE_MAGIC_LEVEL,
	AT_IMPROVE_MAGIC_PERCENT,
	AT_IMPROVE_ATTACK_SPEED,
	AT_IMPROVE_GAIN_LIFE,
	AT_IMPROVE_GAIN_MANA,
	AT_IMPROVE_HP_MAX,
	AT_IMPROVE_MP_MAX,
	AT_ONE_PERCENT_DAMAGE,
	AT_IMPROVE_AG_MAX,
	AT_DAMAGE_ABSORB,
	AT_DAMAGE_REFLECTION,
	AT_RECOVER_FULL_LIFE,
	AT_RECOVER_FULL_MANA,
	AT_IMPROVE_CHARISMA,
	AT_IMPROVE_EVADE = 110,
	AT_SKILL_MONSTER_SUMMON = 200,
	AT_SKILL_MONSTER_MAGIC_DEF,
	AT_SKILL_MONSTER_PHY_DEF,
	AT_SKILL_HELLOWIN_EVENT_1 = 205,
	AT_SKILL_HELLOWIN_EVENT_2 = 206,
	AT_SKILL_HELLOWIN_EVENT_3 = 207,
	AT_SKILL_HELLOWIN_EVENT_4 = 208,
	AT_SKILL_HELLOWIN_EVENT_5 = 209,
	AT_SKILL_CURSED_TEMPLE_PRODECTION = 210,
	AT_SKILL_CURSED_TEMPLE_RESTRAINT = 211,
	AT_SKILL_CURSED_TEMPLE_TELEPORT = 212,
	AT_SKILL_CURSED_TEMPLE_SUBLIMATION = 213,
	AT_SKILL_ALICE_DRAINLIFE = 214,
	AT_SKILL_ALICE_CHAINLIGHTNING = 215,
	AT_SKILL_ALICE_LIGHTNINGORB = 216,
	AT_SKILL_ALICE_THORNS = 217,
	AT_SKILL_ALICE_BERSERKER = 218,
	AT_SKILL_ALICE_SLEEP = 219,
	AT_SKILL_ALICE_BLIND = 220,
	AT_SKILL_ALICE_WEAKNESS = 221,
	AT_SKILL_ALICE_ENERVATION = 222,
	AT_SKILL_SUMMON_EXPLOSION = 223,
	AT_SKILL_SUMMON_REQUIEM = 224,
	AT_SKILL_SUMMON_POLLUTION = 225,
	AT_SKILL_LIGHTNING_SHOCK = 230,
	AT_SKILL_BLOW_OF_DESTRUCTION = 232,
	AT_SKILL_SWELL_OF_MAGICPOWER = 233,
	AT_SKILL_FLAME_STRIKE = 236,
	AT_SKILL_GIGANTIC_STORM = 237,
	AT_SKILL_RECOVER = 234,
	AT_SKILL_MULTI_SHOT = 235,
	AT_SKILL_GAOTIC = 238,
	AT_SKILL_DOPPELGANGER_SELFDESTRUCTION = 239,
	AT_SKILL_THRUST = 260,
	AT_SKILL_STAMP = 261,
	AT_SKILL_GIANTSWING = 262,
	AT_SKILL_DARKSIDE = 263,
	AT_SKILL_DRAGON_LOWER = 264,
	AT_SKILL_DRAGON_KICK = 265,
	AT_SKILL_ATT_UP_OURFORCES = 266,
	AT_SKILL_HP_UP_OURFORCES = 267,
	AT_SKILL_DEF_UP_OURFORCES = 268,
	AT_SKILL_OCCUPY = 269,
	AT_SKILL_PHOENIX_SHOT = 270,
	AT_SKILL_ATTACK_RATEUP = 300,
	AT_SKILL_TOMAN_ATTACKUP = 305,
	AT_SKILL_TOMAN_DEFENCEUP = 310,
	AT_SKILL_DURABLE_MINUS1 = 315,
	AT_SKILL_DURABLE_MINUS2 = 320,
	AT_SKILL_RESIST_UP_POISON = 325,
	AT_SKILL_RESIST_UP_LIGHT = 330,
	AT_SKILL_RESIST_UP_ICE = 335,
	AT_SKILL_AUTO_RECOVER_LIFE = 340,
	AT_SKILL_GET_MONEY_UP = 345,
	AT_SKILL_DEF_UP = 350,
	AT_SKILL_MAX_HP_UP = 355,
	AT_SKILL_MAX_AG_UP = 360,
	AT_SKILL_MANA_RECOVER = 365,
	AT_SKILL_HP_RECOVER = 370,
	AT_SKILL_SD_RECOVER = 375,
	AT_SKILL_EXP_UP = 380,
	AT_SKILL_MAX_SD_UP = 385,
	AT_SKILL_SD_RECOVER_SPD_UP = 390,
	AT_SKILL_MAX_ATTACKRATE_UP = 395,
	AT_SKILL_MIN_ATTACKRATE_UP = 400,
	AT_SKILL_MANA_MINUS_ADD = 405,
	AT_SKILL_MAX_MANA_UP = 410,
	AT_SKILL_MIN_MANA_UP = 415,
	AT_SKILL_PET_DURABLE_SPD_DN = 420,
	AT_SKILL_MAX_ATT_MAGIC_UP = 425,
	AT_SKILL_MIN_ATT_MAGIC_UP = 430,
	AT_SKILL_SOUL_UP = 435,
	AT_SKILL_HELL_FIRE_UP = 440,
	AT_SKILL_EVIL_SPIRIT_UP = 445,
	AT_SKILL_ICE_UP = 450,
	AT_SKILL_TORNADO_SWORDA_UP = 455,
	AT_SKILL_BLOW_UP = 460,
	AT_SKILL_ANGER_SWORD_UP = 465,
	AT_SKILL_LIFE_UP = 470,
	AT_SKILL_HEAL_UP = 475,
	AT_SKILL_DEF_POWER_UP = 480,
	AT_SKILL_ATT_POWER_UP = 485,
	AT_SKILL_MANY_ARROW_UP = 490,
	AT_SKILL_TORNADO_SWORDB_UP = 495,
	AT_SKILL_BLOOD_ATT_UP = 500,
	AT_SKILL_POWER_SLASH_UP = 505,
	AT_SKILL_BLAST_UP = 510,
	AT_SKILL_ASHAKE_UP = 515,
	AT_SKILL_FIRE_BUST_UP = 520,
	AT_SKILL_FIRE_SCREAM_UP = 525,
	AT_SKILL_EVIL_SPIRIT_UP_M = 530,
	AT_SKILL_ALICE_SLEEP_UP = 535,
	AT_SKILL_ALICE_CHAINLIGHTNING_UP = 540,
	AT_SKILL_LIGHTNING_SHOCK_UP = 545,
	AT_SKILL_ALICE_DRAINLIFE_UP = 550,
};

typedef struct DemendConditionInfo
{
	WORD SkillType;
    char SkillName[100];
	WORD SkillLevel;
	WORD SkillStrength;
	WORD SkillDexterity;
	WORD SkillVitality;
	WORD SkillEnergy;
	WORD SkillCharisma;
		
	DemendConditionInfo() : SkillType( 0 ), SkillLevel( 0 ), SkillStrength( 0 ),
		SkillDexterity( 0 ), SkillVitality( 0 ), SkillEnergy( 0 ), SkillCharisma( 0 )
	{
    ZeroMemory( SkillName, 100 );
	}
	BOOL operator<=(const DemendConditionInfo& rhs) const
	{
		return SkillStrength <= rhs.SkillStrength && SkillDexterity <= rhs.SkillDexterity &&
		SkillVitality <= rhs.SkillVitality && SkillEnergy <= rhs.SkillEnergy && SkillCharisma <= rhs.SkillCharisma;
	}
} DemendConditionInfo;

class CSkillManager
{
public:
	CSkillManager();
	virtual ~CSkillManager();
	bool FindHeroSkill(ActionSkillType eSkillType); 
	void GetSkillInformation(int iType, int iLevel, char *lpszName, int *piMana, int *piDistance, int *piSkillMana = NULL);
	void GetSkillInformation_Energy(int iType, int *piEnergy);
	void GetSkillInformation_Charisma(int iType, int *piCharisma);
	float GetSkillDistance(int Index, CHARACTER* c=NULL);
	void GetSkillInformation_Damage(int iType, int *piDamage);
	bool CheckSkillDelay (int SkillIndex);
	void CalcSkillDelay (int time);
	BYTE GetSkillMasteryType (int iType);
	int MasterSkillToBaseSkillIndex(int iMasterSkillIndex);
	bool skillVScharactorCheck( const DemendConditionInfo& basicInfo, const DemendConditionInfo& heroInfo );
	bool DemendConditionCheckSkill(WORD skilltype);
public:

};

extern CSkillManager gSkillManager;